### ISSUE TITLE
Is this is a good theme to port to Backdrop CMS

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/boilerplate#1]
I started this port based upon the request of @domaingood - without any prior experience with this theme. It does seem to have been created with Panopoly in mind. I don't have any experience with Panopoly either. I do see a directory of layouts in the theme, which I assume is a Panopoly thing. 

Any thoughts on why this might be or might not be a good theme to port to Backdrop CMS?

**Comment by domaingood** [comment]
Thanks @stpaultim Hope other members will join to make theme basically who love HTML5 Boilerplate template. https://www.drupal.org/project/boilerplate

**Comment by stpaultim** [comment]
I've been holding off a bit on this in anticipation of the Virtual User Group tomorrow in which we will talk about porting D7 themes to Backdrop. 
https://backdropcms.org/news/events/virtual-user-group-porting-themes-drupal-7

I look forward to getting some feedback and tips on getting started tomorrow.

**Comment by stpaultim** [comment]
I did a little extra looking around at Boilerplate tonight, in advance of VUG tomorrow and I don't think it's as complicated a theme as I expected.

**Comment by stpaultim** [comment]
I've done a little more research and I think I'm comfortable that this will make a good theme framework for Backdrop CMS. 

The theme "works" now. You can load it and enable it without errors. However, we still need to check to see if if all the components of the theme are doing what they are supposed to be doing.
